### ISSUE TITLE
es2017 build

### ISSUE THREAD

**Issue by farfromrefug** [Seb-C/kiss-orm#16]
Could you make you plugin compatible with es2017?
You could use rollup to do that. It is pretty easy to setup build for esm and es5
https://stackoverflow.com/questions/63441311/rollup-esm-and-umd-builds-with-typescript-plugin-and-declarations-not-possible

**Comment by Seb-C** [comment]
I do not understand what you need.
ES being backward-compatible, the es5 build I provide is already compatible with all future versions, including es2017.

**Comment by farfromrefug** [comment]
It is always better to use esm when you can. The v8 runtime for example handles promises natively. 
So you understand better I don't want to use your plugin in a browser. I want to use it in a mobile environment

**Comment by Seb-C** [comment]
In the current state of the ecosystem, ESM modules are a pain to work with and creates a lot of compatibility issues, that is why I am using CommonJS.

When I released this library I also chose es5 and node 8 as a minimal compatible version so it can work with as many stacks as possible. 

Besides, it is a package for NodeJS and (currently) for PostgreSQL, so browsers are not currently supported anyway. For mobile, while it should be possible to use it on a Cordova-like NodeJS backend, it is not currently supported either.

Do you have a specific problem with `kiss-orm` to solve?

**Comment by farfromrefug** [comment]
@Seb-C it was not as part of on issue i had but more because i go for all esm!

**Comment by Seb-C** [comment]
Thanks, I understand, but this is not something I am interested to work on.

If someone made it work and opened a pull-request that does not break anything on my own project, I would welcome it and merge it however ;)
