### ISSUE TITLE
PgSqlDatabase always loaded

### ISSUE THREAD

**Issue by farfromrefug** [Seb-C/kiss-orm#17]
If you use the lib in its current state `PgSqlDatabase` is always loaded. It is an issue when you dont use it but use another Database.
In my case my app cant load because of deep dependencies of postgres which wont work in my environment.
I tried to import what i needed using `kiss-orm/dist/Queries/SqlQuery` to try and prevent the require of `PgSqlDatabase` [here](https://github.com/Seb-C/kiss-orm/blob/master/src/index.ts#L2) but it wont work because you require the index [here](https://github.com/Seb-C/kiss-orm/blob/1f73c10a5fcb59a7e2e4b326fefd9558bdb759f4/src/Repositories/CrudRepository.test.ts#L6)
So could you not import/export from `index.ts` ? Or if you prefer not import `..` from anywhere else?

**Comment by Seb-C** [comment]
Fixed and published in `1.1.1`.
