### ISSUE TITLE
Can't use parameter when searching JSONB column

### ISSUE THREAD

**Issue by dshook** [Seb-C/kiss-orm#25]
Hi, I'm trying to use a parameter to search a JSONB column (named fields in this case) that has an array of name/value objects.

If I specify the value I'm searching for directly it works:
```
  const results = await db.query(sql`
select * from "UserReport" where "fields" @> '[{"Name": "Category", "Value": "Performance"}]'
  `);
```

But when I try to use a parameter to specify what I'm searching for I get an error.
```
  const results = await db.query(sql`
select * from "UserReport" where "fields" @> '[{"Name": "Category", "Value": "${req.query.category}"}]'
  `);```

```

error: bind message supplies 1 parameters, but prepared statement "" requires 0```

Error directly from the db:
```
db_1      | 2020-12-28 04:03:24.099 UTC [74] ERROR:  bind message supplies 1 parameters, but prepared statement "" requires 0
db_1      | 2020-12-28 04:03:24.099 UTC [74] STATEMENT:
db_1      |     select * from "UserReport" where "fields" @> '[{"Name": "Category", "Value": "$1"}]'
db_1      |
```

I've done quite a bit of different quoting alternatives and also made sure all the parameters are there by logging them out in the `queryPoolOrClient` function and they're there so I'm not sure what's going on.

Thanks for the package and taking a look!

**Comment by Seb-C** [comment]
Kiss-orm's syntax is just a convenient wrapper around standard bind parameters. You cannot have a bound parameter inside a litteral.

So you need to have the whole json as a parameter:

```
const results = await db.query(sql`
    select *
    from "UserReport"
    where "fields" @> ${JSON.stringify([{
        "Name": "Category",
        "Value": req.query.category, 
    }])}
  `);
```

I'm writing that from my phone and cannot test right now so there may be mistakes.

You would have to test or check in `node-postgres`'s documentation to know if it is supported or not, but I think it may even work without the `JSON.stringify`.

**Comment by dshook** [comment]
Thanks! That did work (had to include `JSON.stringify`).  It was hard to track down where it was going wrong between the different libraries.
