### ISSUE TITLE
Add MySQL support

### ISSUE THREAD

**Issue by Seb-C** [Seb-C/kiss-orm#26]

**Comment by Seb-C** [comment]
Please note that the MySQL support will be marked as experimental in v2, as I don't need it myself, so cannot test it properly except for the existing unit tests.

**Comment by Seb-C** [comment]
v2 has now been published.

**Comment by farfromrefug** [comment]
@Seb-C updated to 2.0 and it is working like a charm! Thanks a lot for your work
