### ISSUE TITLE
How do you handle nullable/optional fields in Create?

### ISSUE THREAD

**Issue by dshook** [Seb-C/kiss-orm#8]
I have a model that has a number of nullable fields that should be optional to pass when calling create on the repository:

```
class UserReportModel {
  public readonly id!: number;
  public readonly projectId!: string;
  public readonly createdAt!: Date;
  public readonly description?: string;
  public readonly version?: string;
}
```

The id is a serial so I'm doing the suggested removing it from params:
```
type UserReportParams = Omit<UserReportModel, 'id'>;

class UserReportRepository extends CrudRepository<UserReportModel, UserReportParams, number> {
  constructor(database: PgSqlDatabase) {
    super({
      database,
      table: 'UserReport',
      primaryKey: 'id',
      model: UserReportModel,
    });
  }
}
```

When I go to create I get type errors:
```
  await userReportRepository.create({
    projectId: report.ProjectIdentifier,
    createdAt: new Date(),
    description: report.Summary
  });
```
```
(property) description: string
Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

Looks like because the create attributes are `Required` here:
https://github.com/Seb-C/kiss-orm/blob/master/src/Repositories/CrudRepository.ts#L97

**Comment by Seb-C** [comment]
@dshook Apologies for the delay.

The `null` values are handled by `node-postgres` as `null` values, not `undefined`, so you would need to change the type:
```typescript
description: string|null;
```

In the default `create` method, everything is indeed made mandatory but can be nullable. `undefined` values would mean that those fields are not specified in the `INSERT` instruction (thus relying on the default database values).

**Comment by Seb-C** [comment]
I am closing this issue since I added the missing piece of information in the README file. Let me know if you have other questions or problems, and I will reopen it.

**Comment by dshook** [comment]
Thanks for the help and updating the docs :)
